/**
 * Compact provenance contract for the 29 posts imported from
 * Downloads/个人博客素材. The source files themselves stay outside the
 * repository; these anchors are intentionally short, stable excerpts from
 * those read-only originals.
 */
export const IMPORTED_SOURCE_EXPECTATIONS = [
  {
    sourceFile: '26-7-13从十到一百·AI视频影视语言注入指南.html',
    slug: 'from-ten-to-hundred-ai-video',
    title: '从十到一百 · AI 视频影视语言注入指南',
    section: 'ai-mflly-notes',
    publishedAt: '2026-07-13T00:00:00+08:00',
    bodyAnchors: ['影视语言', '六个维度'],
  },
  {
    sourceFile: '26-7-19开发词汇手册 (1).html',
    slug: 'developer-vocabulary-handbook',
    title: '开发词汇手册',
    section: 'yu-studies',
    publishedAt: '2026-07-19T00:00:00+08:00',
    bodyAnchors: ['九个专题', '架构分层'],
  },
  {
    sourceFile: 'AI编程方向概览/AI技术组发展方向与工程化思维分享（上册）.html',
    slug: 'ai-coding-engineering-mindset',
    title: 'AI 技术组发展方向与工程化思维',
    section: 'fullstack-learning',
    publishedAt: '2026-07-29T00:00:00+08:00',
    bodyAnchors: ['树成林 AI 社群技术组', '深度不是终点，广度才是护城河'],
  },
  {
    sourceFile: 'AI编程方向概览/AI编程核心能力体系与工程实践指南（下册）.html',
    slug: 'ai-coding-core-practice',
    title: 'AI 编程核心能力体系与工程实践',
    section: 'fullstack-learning',
    publishedAt: '2026-07-30T00:00:00+08:00',
    bodyAnchors: ['这是第二次分享', '高耦合与低耦合'],
  },
  {
    sourceFile: 'AI编程范式笔记·羽升手记01-v0.3.pdf',
    slug: 'when-we-talk-about-ai-coding',
    title: 'AI编程范式笔记·羽升手记01-v0.3',
    section: 'fullstack-learning',
    publishedAt: '2026-07-13T00:00:00+08:00',
    bodyAnchors: ['这篇东西的起因说起来有点绕', 'harness engineering'],
  },
  {
    sourceFile: '2026年思政课社会实践报告_慧老智治医心为民_宗思阳团队.docx',
    slug: 'hui-lao-zhi-zhi-practice',
    title: '慧老智治 医心为民：AI 智慧医养与基层养老治理',
    section: 'other',
    publishedAt: '2026-08-30T00:00:00+08:00',
    bodyAnchors: ['人口老龄化是当今中国最显著的社会变迁之一', 'AI智慧医养赋能基层养老治理现代化'],
  },
  {
    sourceFile: '自我认知与职业生涯规划课报告.txt',
    slug: 'career-planning-course-report',
    title: '自我认知与职业生涯规划课报告',
    section: 'other',
    publishedAt: '2026-05-29T00:00:00+08:00',
    bodyAnchors: ['个人专业是基医强基', '人工智能和全栈开发方向非常感兴趣'],
  },
  {
    sourceFile: 'AI时代教育变革与课程体系建设思考_2026年08月30日00时53分31秒.txt',
    slug: 'education-in-the-ai-era',
    title: 'AI 时代的教育变革与课程体系建设',
    section: 'other',
    publishedAt: '2026-08-30T00:53:31+08:00',
    bodyAnchors: ['人工智能概论书', 'AI编程和AI生图衍生视频'],
  },
  {
    sourceFile: 'AI智能体技术原理与行业趋势分享_2026年08月30日00时59分45秒.txt',
    slug: 'agent-principles-and-trends',
    title: 'Agent的简单理解',
    section: 'fullstack-learning',
    publishedAt: '2026-08-08T00:00:00+08:00',
    bodyAnchors: ['智能体方面的需求很大', '阿尔法go'],
  },
  {
    sourceFile: 'Ai深度学习计划.txt',
    slug: 'ai-deep-learning-plan',
    title: '25-12-9 AI 深度学习计划',
    section: 'yu-reviews',
    publishedAt: '2025-12-09T00:00:00+08:00',
    bodyAnchors: ['经过大一几个月的探索', '目前的首要目的ai分类'],
  },
  {
    sourceFile: '博客素材816。.txt',
    slug: 'open-models-and-watermarks',
    title: '26-8-15 复盘 · 开源模型廉价智能和水印',
    section: 'ai-mflly-notes',
    publishedAt: '2026-08-15T00:00:00+08:00',
    bodyAnchors: ['未来肯定会以更廉价的智能去提供ai服务', '水印的问题'],
  },
  {
    sourceFile: '10月份总结.txt',
    slug: 'october-busy-and-growth',
    title: '25年10月复盘 · 认知、忙碌、成长',
    section: 'yu-reviews',
    publishedAt: '2025-11-02T00:00:00+08:00',
    bodyAnchors: ['时间真的是飞逝', '百团大战'],
  },
  {
    sourceFile: '7-28日总结反思_2026年08月30日01时00分30秒.txt',
    slug: 'july-28-ai-frontier-review',
    title: '26-7-28 复盘 · AI方向如是状态',
    section: 'yu-reviews',
    publishedAt: '2026-07-28T00:00:00+08:00',
    bodyAnchors: ['Hello这是第一天的正式复盘', 'AI编程方面的东西'],
  },
  {
    sourceFile: '20250804突然的小反思.txt',
    slug: 'when-energy-runs-low',
    title: '25-8-4 复盘 · 能量低的那天',
    section: 'yu-reviews',
    publishedAt: '2025-08-04T00:00:00+08:00',
    bodyAnchors: ['我现在在用微信的语音转文字', '小说去舒缓舒缓吧'],
  },
  {
    sourceFile: '个人财务基础分析与反思.txt',
    slug: 'personal-finance-and-ai-dev',
    title: '26-8-26 个人财务复盘',
    section: 'yu-reviews',
    publishedAt: '2026-08-26T00:00:00+08:00',
    bodyAnchors: ['我个人非常穷', '摄影和剪辑这方面'],
  },
  {
    sourceFile: '医学生转码血泪史 ┃ 注意身体.txt',
    slug: 'med-student-coding-and-health',
    title: '26-2-19 复盘 · 医学生转码血泪史｜注意身体',
    section: 'yu-reviews',
    publishedAt: '2026-02-19T00:00:00+08:00',
    bodyAnchors: ['哈喽大家好，我是羽升', '健康永远是第一'],
  },
  {
    sourceFile: '浅涉谈爱情.txt',
    slug: 'on-love-a-first-pass',
    title: '浅涉谈爱情',
    section: 'yu-reflections',
    publishedAt: '2025-10-20T00:00:00+08:00',
    bodyAnchors: ['谈的这一场异地恋', '拯救式恋爱恐怕真的难以长久'],
  },
  {
    sourceFile: '备忘录文档_202608300114.docx',
    slug: 'september-ninth-new-self',
    title: '25-9-9 复盘 · 九月九日新的自己',
    section: 'yu-reviews',
    publishedAt: '2025-09-09T00:00:00+08:00',
    bodyAnchors: ['真的感谢大一开学遇到滴一些事情', '人生管道模型'],
  },
  {
    sourceFile: '修为规则.txt',
    slug: 'cultivation-rules-of-feixing',
    title: '飞星大陆的修为规则',
    section: 'yu-essays',
    publishedAt: '2025-07-07T00:00:00+08:00',
    bodyAnchors: ['初稿，飞星大陆乃是修真不胜之地', '修炼本质提升的是血量'],
  },
  {
    sourceFile: '兴许对于一位刚刚接触剪辑的人而言.txt',
    slug: 'editing-quantity-to-quality',
    title: '剪辑&质变与量变的简单理解',
    section: 'yu-essays',
    publishedAt: '2026-02-06T00:00:00+08:00',
    bodyAnchors: ['兴许对于一位刚刚接触剪辑的人而言', '自然辩证法'],
  },
  {
    sourceFile: '军训有感（极速版）.txt',
    slug: 'military-training-notes',
    title: '军训有感',
    section: 'yu-essays',
    publishedAt: '2025-09-04T00:00:00+08:00',
    bodyAnchors: ['军训时不由会思考一个问题', '无数革命先辈洒血沙场'],
  },
  {
    sourceFile: '感悟 - 回归本真.txt',
    slug: 'return-to-the-essence',
    title: '回归本真',
    section: 'yu-essays',
    publishedAt: '2025-12-26T00:00:00+08:00',
    bodyAnchors: ['曾经我也是蛮热爱文字的', '少年自有青云志'],
  },
  {
    sourceFile: '备忘录文档_202608300109.docx',
    slug: 'absorption-as-digestion',
    title: '吸收，是消化而不是堆砌',
    section: 'yu-essays',
    publishedAt: '2025-12-26T12:00:00+08:00',
    bodyAnchors: ['个人理解主要是吸收固然重要', '量变引起质变'],
  },
  {
    sourceFile: '毕业升学  一寸光阴的曾经.txt',
    slug: 'graduation-and-one-inch-time',
    title: '毕业升学 · 一寸光阴的曾经',
    section: 'yu-essays',
    publishedAt: '2025-07-15T00:00:00+08:00',
    bodyAnchors: ['亲爱的九中三班战友们', '倒计时20天'],
  },
  {
    sourceFile: '源远流长（随笔）.txt',
    slug: 'visiting-the-ancestors',
    title: '源远流长',
    section: 'yu-essays',
    publishedAt: '2025-08-23T00:00:00+08:00',
    bodyAnchors: ['前行路上，异于常日于车中品读玄幻小说', '祖父之墓'],
  },
  {
    sourceFile: '自我介绍~过渡.txt',
    slug: 'self-intro-in-transition',
    title: '一份中二的自我介绍',
    section: 'yu-essays',
    publishedAt: '2025-11-12T00:00:00+08:00',
    bodyAnchors: ['华科基医强基2501 孔德羽', '最开始接触剪辑摄影ppt'],
  },
  {
    sourceFile: '说一说和树林的故事(1).txt',
    slug: 'stories-with-the-woods',
    title: '说一说和树林的故事',
    section: 'yu-essays',
    publishedAt: '2026-03-10T00:00:00+08:00',
    bodyAnchors: ['提到这个问题，突然想到树林昨天的直播', 'ai是一个很好的复盘对象'],
  },
  {
    sourceFile: '那么就让AI顺便也入侵一下科幻吧.txt',
    slug: 'let-ai-invade-science-fiction',
    title: '那么就让 AI 顺便也入侵一下科幻吧',
    section: 'yu-essays',
    publishedAt: '2025-10-31T00:00:00+08:00',
    bodyAnchors: ['引领我走入科幻这扇万千大门', '幻海航行，用心讲述每一个故事'],
  },
  {
    sourceFile: '备忘录文档_202608300123.docx',
    slug: 'after-watching-malice',
    title: '《恶意》观后感',
    section: 'yu-essays',
    publishedAt: '2025-07-08T00:00:00+08:00',
    bodyAnchors: ['这部电影让我感触最深的', '思绪至此，与诸君共勉'],
  },
] as const

export type ImportedSourceExpectation = (typeof IMPORTED_SOURCE_EXPECTATIONS)[number]
