/** Official posts imported from Downloads/个人博客素材 in this goal. */
export const IMPORTED_SLUGS = [
  'from-ten-to-hundred-ai-video',
  'developer-vocabulary-handbook',
  'ai-coding-engineering-mindset',
  'ai-coding-core-practice',
  'when-we-talk-about-ai-coding',
  'hui-lao-zhi-zhi-practice',
  'career-planning-course-report',
  'education-in-the-ai-era',
  'agent-principles-and-trends',
  'ai-deep-learning-plan',
  'open-models-and-watermarks',
  'october-busy-and-growth',
  'july-28-ai-frontier-review',
  'when-energy-runs-low',
  'personal-finance-and-ai-dev',
  'med-student-coding-and-health',
  'on-love-a-first-pass',
  'september-ninth-new-self',
  'cultivation-rules-of-feixing',
  'editing-quantity-to-quality',
  'military-training-notes',
  'return-to-the-essence',
  'absorption-as-digestion',
  'graduation-and-one-inch-time',
  'visiting-the-ancestors',
  'self-intro-in-transition',
  'stories-with-the-woods',
  'let-ai-invade-science-fiction',
  'after-watching-malice',
] as const
